# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.click_pos_le = QtWidgets.QLineEdit(self.centralwidget)
        self.click_pos_le.setEnabled(False)
        self.click_pos_le.setGeometry(QtCore.QRect(190, 90, 113, 42))
        self.click_pos_le.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.click_pos_le.setObjectName("click_pos_le")
        self.interval_le = QtWidgets.QLineEdit(self.centralwidget)
        self.interval_le.setGeometry(QtCore.QRect(190, 240, 113, 42))
        self.interval_le.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.interval_le.setObjectName("interval_le")
        self.click_time_le = QtWidgets.QLineEdit(self.centralwidget)
        self.click_time_le.setGeometry(QtCore.QRect(190, 290, 113, 42))
        self.click_time_le.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.click_time_le.setObjectName("click_time_le")
        self.mouse_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mouse_groupBox.setGeometry(QtCore.QRect(190, 140, 221, 41))
        self.mouse_groupBox.setAutoFillBackground(False)
        self.mouse_groupBox.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"border:0px;")
        self.mouse_groupBox.setTitle("")
        self.mouse_groupBox.setObjectName("mouse_groupBox")
        self.click_way_rb1 = QtWidgets.QRadioButton(self.mouse_groupBox)
        self.click_way_rb1.setGeometry(QtCore.QRect(0, 10, 115, 19))
        self.click_way_rb1.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
"")
        self.click_way_rb1.setObjectName("click_way_rb1")
        self.click_way_rb2 = QtWidgets.QRadioButton(self.mouse_groupBox)
        self.click_way_rb2.setGeometry(QtCore.QRect(120, 10, 115, 19))
        self.click_way_rb2.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
"")
        self.click_way_rb2.setObjectName("click_way_rb2")
        self.mouse_groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.mouse_groupBox_2.setEnabled(True)
        self.mouse_groupBox_2.setGeometry(QtCore.QRect(190, 190, 221, 41))
        self.mouse_groupBox_2.setMouseTracking(False)
        self.mouse_groupBox_2.setAutoFillBackground(False)
        self.mouse_groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"border:0px;")
        self.mouse_groupBox_2.setTitle("")
        self.mouse_groupBox_2.setObjectName("mouse_groupBox_2")
        self.mouse_choose_rb2 = QtWidgets.QRadioButton(self.mouse_groupBox_2)
        self.mouse_choose_rb2.setGeometry(QtCore.QRect(120, 10, 115, 19))
        self.mouse_choose_rb2.setStyleSheet("font: 12pt \"方正粗黑宋简体\";")
        self.mouse_choose_rb2.setObjectName("mouse_choose_rb2")
        self.mouse_choose_rb1 = QtWidgets.QRadioButton(self.mouse_groupBox_2)
        self.mouse_choose_rb1.setGeometry(QtCore.QRect(0, 10, 115, 19))
        self.mouse_choose_rb1.setStyleSheet("font: 12pt \"方正粗黑宋简体\";")
        self.mouse_choose_rb1.setObjectName("mouse_choose_rb1")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 90, 134, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.click_pos_label = QtWidgets.QLabel(self.layoutWidget)
        self.click_pos_label.setAutoFillBackground(False)
        self.click_pos_label.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.click_pos_label.setObjectName("click_pos_label")
        self.verticalLayout.addWidget(self.click_pos_label)
        self.click_way_label = QtWidgets.QLabel(self.layoutWidget)
        self.click_way_label.setAutoFillBackground(False)
        self.click_way_label.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.click_way_label.setObjectName("click_way_label")
        self.verticalLayout.addWidget(self.click_way_label)
        self.mouse_choose_label = QtWidgets.QLabel(self.layoutWidget)
        self.mouse_choose_label.setAutoFillBackground(False)
        self.mouse_choose_label.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.mouse_choose_label.setObjectName("mouse_choose_label")
        self.verticalLayout.addWidget(self.mouse_choose_label)
        self.interval_label = QtWidgets.QLabel(self.layoutWidget)
        self.interval_label.setAutoFillBackground(False)
        self.interval_label.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.interval_label.setObjectName("interval_label")
        self.verticalLayout.addWidget(self.interval_label)
        self.click_time = QtWidgets.QLabel(self.layoutWidget)
        self.click_time.setAutoFillBackground(False)
        self.click_time.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.click_time.setObjectName("click_time")
        self.verticalLayout.addWidget(self.click_time)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 501, 401))
        self.graphicsView.setStyleSheet("background-image: url(:/img/mouse.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 401, 31))
        self.label.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 491, 31))
        self.label_2.setStyleSheet("font: 13pt \"方正粗黑宋简体\";\n"
"background-color: rgb(255, 255,255,0);")
        self.label_2.setObjectName("label_2")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(280, 340, 111, 41))
        self.start_btn.setStyleSheet("font: 10pt \"方正粗黑宋简体\";")
        self.start_btn.setObjectName("start_btn")
        self.choose_pos_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_pos_btn.setGeometry(QtCore.QRect(90, 340, 121, 41))
        self.choose_pos_btn.setStyleSheet("font: 10pt \"方正粗黑宋简体\";")
        self.choose_pos_btn.setObjectName("choose_pos_btn")
        self.graphicsView.raise_()
        self.click_pos_le.raise_()
        self.interval_le.raise_()
        self.click_time_le.raise_()
        self.mouse_groupBox.raise_()
        self.mouse_groupBox_2.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.start_btn.raise_()
        self.choose_pos_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setWindowIcon(QIcon("log.ico"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "鼠标点击器—JustD2019"))
        self.click_way_rb1.setText(_translate("MainWindow", "单击"))
        self.click_way_rb2.setText(_translate("MainWindow", "双击"))
        self.mouse_choose_rb2.setText(_translate("MainWindow", "右键"))
        self.mouse_choose_rb1.setText(_translate("MainWindow", "左键"))
        self.click_pos_label.setText(_translate("MainWindow", "单击坐标"))
        self.click_way_label.setText(_translate("MainWindow", "单双击选择"))
        self.mouse_choose_label.setText(_translate("MainWindow", "左右键选择"))
        self.interval_label.setText(_translate("MainWindow", "点击间隔(秒)"))
        self.click_time.setText(_translate("MainWindow", "点击次数"))
        self.label.setText(_translate("MainWindow", "提示：请将本程序置顶后使用"))
        self.label_2.setText(_translate("MainWindow", "若要提前结束程序请将鼠标移动到电脑屏幕左上角"))
        self.start_btn.setText(_translate("MainWindow", "开始(F10)"))
        self.choose_pos_btn.setText(_translate("MainWindow", "选择坐标(F9)"))
import mysource_rc
